---
name: CI

'on':
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-build:
    name: Test and build
    uses: drugscom/shared-workflows/.github/workflows/gh-actions-node-ci.yml@v1
